### ISSUE TITLE
example/editor yarn build error

### ISSUE THREAD

**Issue by MacroMachines** [fand/vedajs#17]
noticed in src/index.js the top line is `import Veda from '../../..';`
getting terminal error on yarn build:

`ERROR in ./src/index.js
Module not found: Error: Can't resolve '../../..' in '/Users/nicholascraftisiii/Google Drive/Kinetic Create/Work in Progress/JS WebGL/vedajs-master/examples/editor/src'
 @ ./src/index.js 1:0-28
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js
webpack: Failed to compile.
webpack: Compiling...
Hash: 9f6b5d0f874d70527ed5
Version: webpack 3.7.1
Time: 65ms
 1 asset
  [83] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
    + 87 hidden modules`

I do get a split screen with text entry at the localhost:8080 but tried pasting in the example from atom to see if anything happens but no luck:

`precision mediump float;
uniform float time;
uniform vec2 resolution;

void main() {
    vec2 uv = gl_FragCoord.xy / resolution.xy;
    gl_FragColor = vec4(uv, 0.5 + 0.5 * sin(time), 1.0);
}
`

**Comment by fand** [comment]
ah, maybe it's because `vedajs-master/lib` is not found.
you can get it working by first run `yarn build` at `vedajs-master` directory. @MacroMachines 

I gotta fix examples to work without building..

**Comment by fand** [comment]
Fixed in `910852d` .
Plz pull and run `yarn && yarn start` in `examples/editor` ! @MacroMachines
